/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertAdult: typeof import('./src/components/AlertAdult.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ButtonDefault: typeof import('./src/components/ButtonDefault.vue')['default']
    Card: typeof import('primevue/card')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataView: typeof import('primevue/dataview')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FooterDefault: typeof import('./src/components/FooterDefault.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
